[font]
  size = 12.0
[font.normal]
  family = 'Cascadia Code'
  style = 'Regular'
[font.bold]
  family = 'Cascadia Code'
  style = 'Bold'
[font.italic]
  family = 'Cascadia Code'
  style = 'Italic'
[font.bold_italic]
  family = 'Cascadia Code'
  style = 'Bold Italic'


# === Colors ===
# Colors (Gruvbox Material Medium Dark)

# Default colors
[colors]
[colors.primary]
background = '#282828'
foreground = '#d4be98'

[colors.normal]
black   = '#3c3836'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'

[colors.bright]
black   = '#3c3836'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'

[window]
opacity = 0.8

[window.dimensions]
columns = 80
lines   = 23

